#!/bin/bash
export SCRIPT_NAME='kubeforward'
export AMOUNT_ARGUMENTS='3'
export USAGE='<namespace> <servicename> <localPort:remotePort>'

source base

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
    echo "todo let base do it for you"
    echo "requires $AMOUNT_ARGUMENTS arguments"
    echo "usage: $SCRIPT_NAME $USAGE"
    exit 1
fi

echo "todo let base do it for you"
PORTMAPPING=$3

kubectl port-forward --namespace "$NAMESPACE" "$(kubectl get pods --namespace "$NAMESPACE" | ag "$SERVICENAME" |cut -d ' ' -f1)" "$PORTMAPPING"